default: &default
  adapter: "postgresql"
  encoding: "unicode"
  database: "<%= ENV.fetch("POSTGRES_DB") { "ecommerce" } %>"
  username: "<%= ENV.fetch("POSTGRES_USER") { "hello" } %>"
  password: "<%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>"
  host: "<%= ENV.fetch("POSTGRES_HOST") { "postgres" } %>"
  port: "<%= ENV.fetch("POSTGRES_PORT") { 5432 } %>"
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: "<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>"

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "ecommerce" } %>_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "ecommerce" } %>_test

production:
  encoding: utf8
  database: ecommerce_production
  username: <%= ENV.fetch("DB_USER") { "user" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("DB_HOST") { "host" } %>
